name: Deploy to GitHub Pages

on:
  push:
    # Trigger this workflow whenever code is pushed to the 'main' branch
    branches:
      - main
  # Allows manual deployment from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build
        env:
          # Inject the GitHub Secret into the shell environment for the build command
          # The key is VITE_TMDB_API_KEY (from your secret) = $VITE_TMDB_API_KEY (the secret value)
          VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The resulting build files are in the 'dist' folder
          publish_dir: ./dist
          # Set this to true if you are using a custom domain
          # cname: example.com 
